### ISSUE TITLE
flutterfire_gen と riverpod_generator を合わせて使おうとした際、build_runner が失敗する

### ISSUE THREAD

**Issue by kato-kyo** [kosukesaigusa/flutterfire_gen#2]
## 概要
flutterfire_gen と riverpod_generator を合わせて使おうとした際、build_runner の build コマンドで
それぞれの自動生成ファイルはできるものの、build_runner の実行結果はエラーになると言う事象があったので報告します。

## 再現環境
fvm flutter --version
```
Flutter 3.13.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 367f9ea16b (4 weeks ago) • 2023-09-12 23:27:53 -0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0
```

* 再現したサンプルプロジェクトです。
https://github.com/sukekyo-net/ffgen_sample

* 実行コマンド
fvm flutter pub run build_runner build --delete-conflicting-outputs -v

## 考察
build_runner のログからの推察ですが、 riverpod_generator が生成する .g.dart (partファイル) を扱おうとした際の例外が、
そのまま build_runner まで throw されてエラー判定になってしまっている と想像します。

### エラー要因と思われるビルドログ

```
Asset [ffgen_sample|lib/user.g.dart] is not a Dart library. It may be a part file or a file without Dart source code.
package:build_resolvers/src/resolver.dart 259:17             AnalyzerResolver.libraryFor.<fn>.<fn>
package:pool/pool.dart 127:28                                Pool.withResource
package:build_resolvers/src/shared_resource_pool.dart 45:14  SharedResourcePool.withSharedResource
package:build_resolvers/src/resolver.dart 249:21             AnalyzerResolver.libraryFor
package:flutterfire_gen/flutterfire_gen.dart 24:21           _FlutterfireGenBuilder.build
```

### ログの該当ソース

> Asset [ffgen_sample|lib/user.g.dart] is not a Dart library. It may be a part file or a file without Dart source code.
/Users/xxxx/.pub-cache/hosted/pub.dev/build-2.4.1/lib/src/analyzer/resolver.dart
```
class NonLibraryAssetException implements Exception {
  final AssetId assetId;

  const NonLibraryAssetException(this.assetId);

  @override
  String toString() => 'Asset [$assetId] is not a Dart library. '
      'It may be a part file or a file without Dart source code.';
}
```

> package:build_resolvers/src/resolver.dart 259:17             AnalyzerResolver.libraryFor.<fn>.<fn>
```
  var path = assetPath(assetId);
  var parsedResult = _driver.currentSession.getParsedUnit(path);
  if (parsedResult is! ParsedUnitResult || parsedResult.isPart) {
    throw NonLibraryAssetException(assetId);                               // Line: 259 ここ
  }

  return await _driver.currentSession
      .getLibraryByUri(uri.toString()) as LibraryElementResult;
}));
```

> package:flutterfire_gen/flutterfire_gen.dart 24:21           _FlutterfireGenBuilder.build
```
  @override
  Future<void> build(BuildStep buildStep) async {
    final assetId = buildStep.inputId;
    final outputId = assetId.changeExtension('.flutterfire_gen.dart');
    final library = await buildStep.inputLibrary;                          // Line: 24 ここで例外を投げると失敗する？
    if (!_firestoreDocumentAnnotationFound(library)) {
      return;
    }
```

**Comment by kosukesaigusa** [comment]
@sukekyo-net 

Issue 作成ありがとうございます！

まだ正式リリースしていないので、これからどんどん長期的に直していきます！

それまで申し訳ないですが待っていただけると幸いです！

**Comment by kosukesaigusa** [comment]
@sukekyo-net 

Thank you for reporting an issue!

After entirely refactor and udpate flutterfire_gen package, the example app here:

https://github.com/kosukesaigusa/flutterfire_gen/tree/main/examples/todo

shows it successfully build with riverpod_generator.

Try to use the latest version of flutterfire_gen now!

I will close the issue, but if you find any problems later, please reopen or create a new one!
