### ISSUE TITLE
Not compatible with firestore 5.x.x

### ISSUE THREAD

**Issue by masa-tokyo** [kosukesaigusa/flutterfire_gen#72]
@kosukesaigusa 
Thank you very much for the wonderful package!
I would appreciate it if this becomes compatible with the firestore latest version, which is 5.x.x.
To resolve this, I made https://github.com/kosukesaigusa/flutterfire_gen/pull/71.
Please consider releasing a newer version including this update :)

**Comment by kosukesaigusa** [comment]
Thank you for creating an issue and a PR @masa-tokyo!

The new version `0.5.0` of both of flutterfire_gen and flutterfire_gen_utils are now available!

- https://pub.dev/packages/flutterfire_gen
- https://pub.dev/packages/flutterfire_gen_utils

**Comment by masa-tokyo** [comment]
@kosukesaigusa 
I really appreciate the quick response! 
Thank you!!
